package theradproject;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ThreadForm extends javax.swing.JFrame {

    private ArrayList<GuiElements> guiElements;

    private long lookForPrime;

    public static boolean isDone = true;
    private boolean start = true;

    private Thread th; // Otomatik işlem yapan thread

    private SqlClass sql;

    private int threadCount; // Gerekli olan thread sayısı

    // Asal sayı kontrolü yapan threadlerin tutulduğu liste
    private ArrayList<Thread> threadClassArrayList = new ArrayList<>();

    public ThreadForm() {
        sql = SqlClass.getInstance(); // Sql işlemlerinin yapıldı sınıf
        sql.ConnectToTable();

        guiElements = new ArrayList<>();

        // Tablodaki en büyük asal sayının iki fazlası kontrol ediliyor her defasında
        // todo burayı düzelt
        lookForPrime = sql.getMaxFromTable() + 2;

        initComponents();
        addComponentsToList();
    }

    private void addComponentsToList() {

        guiElements.add(new GuiElements(jPanel1, threadLabel, baslangicLabel, bitisLabel, durumLabel));
        guiElements.add(new GuiElements(jPanel2, threadLabel1, baslangicLabel1, bitisLabel1, durumLabel1));
        guiElements.add(new GuiElements(jPanel8, threadLabel7, baslangicLabel7, bitisLabel7, durumLabel7));
        guiElements.add(new GuiElements(jPanel9, threadLabel8, baslangicLabel8, bitisLabel8, durumLabel8));
        guiElements.add(new GuiElements(jPanel10, threadLabel9, baslangicLabel9, bitisLabel9, durumLabel9));
        guiElements.add(new GuiElements(jPanel11, threadLabel10, baslangicLabel10, bitisLabel10, durumLabel10));
        guiElements.add(new GuiElements(jPanel12, threadLabel11, baslangicLabel11, bitisLabel11, durumLabel11));
        guiElements.add(new GuiElements(jPanel13, threadLabel12, baslangicLabel12, bitisLabel12, durumLabel12));
        guiElements.add(new GuiElements(jPanel14, threadLabel13, baslangicLabel13, bitisLabel13, durumLabel13));
        guiElements.add(new GuiElements(jPanel15, threadLabel14, baslangicLabel14, bitisLabel14, durumLabel14));
        guiElements.add(new GuiElements(jPanel16, threadLabel15, baslangicLabel15, bitisLabel15, durumLabel15));
        guiElements.add(new GuiElements(jPanel17, threadLabel16, baslangicLabel16, bitisLabel16, durumLabel16));

        for (int i = 0; i < guiElements.size(); i++) {
            guiElements.get(i).getjPanel().setVisible(false);
            guiElements.get(i).getThreadLabel().setVisible(false);
            guiElements.get(i).getDurumLabel().setVisible(false);
            guiElements.get(i).getDurumLabel().setOpaque(true);
            guiElements.get(i).getBitisLabel().setVisible(false);
            guiElements.get(i).getBaslangicLabel().setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        solPanel = new javax.swing.JPanel();
        bitisYaziLabel = new javax.swing.JLabel();
        baslangicYaziLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        threadLabel = new javax.swing.JLabel();
        baslangicLabel = new javax.swing.JLabel();
        bitisLabel = new javax.swing.JLabel();
        durumLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        threadLabel1 = new javax.swing.JLabel();
        baslangicLabel1 = new javax.swing.JLabel();
        bitisLabel1 = new javax.swing.JLabel();
        durumLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        threadLabel7 = new javax.swing.JLabel();
        baslangicLabel7 = new javax.swing.JLabel();
        bitisLabel7 = new javax.swing.JLabel();
        durumLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        threadLabel8 = new javax.swing.JLabel();
        baslangicLabel8 = new javax.swing.JLabel();
        bitisLabel8 = new javax.swing.JLabel();
        durumLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        threadLabel9 = new javax.swing.JLabel();
        baslangicLabel9 = new javax.swing.JLabel();
        bitisLabel9 = new javax.swing.JLabel();
        durumLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        threadLabel10 = new javax.swing.JLabel();
        baslangicLabel10 = new javax.swing.JLabel();
        bitisLabel10 = new javax.swing.JLabel();
        durumLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        threadLabel11 = new javax.swing.JLabel();
        baslangicLabel11 = new javax.swing.JLabel();
        bitisLabel11 = new javax.swing.JLabel();
        durumLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        threadLabel12 = new javax.swing.JLabel();
        baslangicLabel12 = new javax.swing.JLabel();
        bitisLabel12 = new javax.swing.JLabel();
        durumLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        threadLabel13 = new javax.swing.JLabel();
        baslangicLabel13 = new javax.swing.JLabel();
        bitisLabel13 = new javax.swing.JLabel();
        durumLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        threadLabel14 = new javax.swing.JLabel();
        baslangicLabel14 = new javax.swing.JLabel();
        bitisLabel14 = new javax.swing.JLabel();
        durumLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        threadLabel15 = new javax.swing.JLabel();
        baslangicLabel15 = new javax.swing.JLabel();
        bitisLabel15 = new javax.swing.JLabel();
        durumLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        threadLabel16 = new javax.swing.JLabel();
        baslangicLabel16 = new javax.swing.JLabel();
        bitisLabel16 = new javax.swing.JLabel();
        durumLabel16 = new javax.swing.JLabel();
        sagUstPanel = new javax.swing.JPanel();
        baslaButton = new javax.swing.JButton();
        bitirButton = new javax.swing.JButton();
        arastirilanLabel = new javax.swing.JLabel();
        sayiLabel = new javax.swing.JLabel();
        sagAltPanel = new javax.swing.JPanel();
        sonucLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sonucArea = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thread Primes");
        setBackground(new java.awt.Color(113, 114, 215));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        solPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        solPanel.setName(""); // NOI18N

        bitisYaziLabel.setText("Bitiş Noktası");

        baslangicYaziLabel.setText("Başlangıç Noktası");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel.setText("Thread0");

        baslangicLabel.setText("jLabel4");

        bitisLabel.setText("jLabel5");

        durumLabel.setText("true");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(durumLabel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel)
                    .addComponent(baslangicLabel)
                    .addComponent(bitisLabel)
                    .addComponent(durumLabel)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel1.setText("Thread0");

        baslangicLabel1.setText("jLabel4");

        bitisLabel1.setText("jLabel5");

        durumLabel1.setText("true");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel1)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel1)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel1)
                    .addComponent(baslangicLabel1)
                    .addComponent(bitisLabel1)
                    .addComponent(durumLabel1)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel7.setText("Thread0");

        baslangicLabel7.setText("jLabel4");

        bitisLabel7.setText("jLabel5");

        durumLabel7.setText("true");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel7)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel7)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel7)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel7)
                    .addComponent(baslangicLabel7)
                    .addComponent(bitisLabel7)
                    .addComponent(durumLabel7)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel8.setText("Thread0");

        baslangicLabel8.setText("jLabel4");

        bitisLabel8.setText("jLabel5");

        durumLabel8.setText("true");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel8)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel8)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel8)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel8)
                    .addComponent(baslangicLabel8)
                    .addComponent(bitisLabel8)
                    .addComponent(durumLabel8)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel9.setText("Thread0");

        baslangicLabel9.setText("jLabel4");

        bitisLabel9.setText("jLabel5");

        durumLabel9.setText("true");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel9)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel9)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel9)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel9)
                    .addComponent(baslangicLabel9)
                    .addComponent(bitisLabel9)
                    .addComponent(durumLabel9)))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel10.setText("Thread0");

        baslangicLabel10.setText("jLabel4");

        bitisLabel10.setText("jLabel5");

        durumLabel10.setText("true");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel10)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel10)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel10)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel10)
                    .addComponent(baslangicLabel10)
                    .addComponent(bitisLabel10)
                    .addComponent(durumLabel10)))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel11.setText("Thread0");

        baslangicLabel11.setText("jLabel4");

        bitisLabel11.setText("jLabel5");

        durumLabel11.setText("true");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel11)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel11)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel11)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel11)
                    .addComponent(baslangicLabel11)
                    .addComponent(bitisLabel11)
                    .addComponent(durumLabel11)))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel12.setText("Thread0");

        baslangicLabel12.setText("jLabel4");

        bitisLabel12.setText("jLabel5");

        durumLabel12.setText("true");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel12)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel12)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel12)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel12)
                    .addComponent(baslangicLabel12)
                    .addComponent(bitisLabel12)
                    .addComponent(durumLabel12)))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel13.setText("Thread0");

        baslangicLabel13.setText("jLabel4");

        bitisLabel13.setText("jLabel5");

        durumLabel13.setText("true");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel13)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel13)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel13)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel13)
                    .addComponent(baslangicLabel13)
                    .addComponent(bitisLabel13)
                    .addComponent(durumLabel13)))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel14.setText("Thread0");

        baslangicLabel14.setText("jLabel4");

        bitisLabel14.setText("jLabel5");

        durumLabel14.setText("true");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel14)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel14)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel14)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel14)
                    .addComponent(baslangicLabel14)
                    .addComponent(bitisLabel14)
                    .addComponent(durumLabel14)))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel15.setText("Thread0");

        baslangicLabel15.setText("jLabel4");

        bitisLabel15.setText("jLabel5");

        durumLabel15.setText("true");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel15)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel15)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel15)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel15)
                    .addComponent(baslangicLabel15)
                    .addComponent(bitisLabel15)
                    .addComponent(durumLabel15)))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        threadLabel16.setText("Thread0");

        baslangicLabel16.setText("jLabel4");

        bitisLabel16.setText("jLabel5");

        durumLabel16.setText("true");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadLabel16)
                .addGap(38, 38, 38)
                .addComponent(baslangicLabel16)
                .addGap(117, 117, 117)
                .addComponent(bitisLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(durumLabel16)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadLabel16)
                    .addComponent(baslangicLabel16)
                    .addComponent(bitisLabel16)
                    .addComponent(durumLabel16)))
        );

        javax.swing.GroupLayout solPanelLayout = new javax.swing.GroupLayout(solPanel);
        solPanel.setLayout(solPanelLayout);
        solPanelLayout.setHorizontalGroup(
            solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(solPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(baslangicYaziLabel)
                        .addGap(45, 45, 45)
                        .addComponent(bitisYaziLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        solPanelLayout.setVerticalGroup(
            solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solPanelLayout.createSequentialGroup()
                .addGroup(solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baslangicYaziLabel)
                    .addComponent(bitisYaziLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        sagUstPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        baslaButton.setText("Başla");
        baslaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslaButtonActionPerformed(evt);
            }
        });

        bitirButton.setText("Bitir");
        bitirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirButtonActionPerformed(evt);
            }
        });

        arastirilanLabel.setText("Araştırılan Sayı : ");

        sayiLabel.setText("Sayı");

        javax.swing.GroupLayout sagUstPanelLayout = new javax.swing.GroupLayout(sagUstPanel);
        sagUstPanel.setLayout(sagUstPanelLayout);
        sagUstPanelLayout.setHorizontalGroup(
            sagUstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagUstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sagUstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sagUstPanelLayout.createSequentialGroup()
                        .addComponent(arastirilanLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sayiLabel))
                    .addGroup(sagUstPanelLayout.createSequentialGroup()
                        .addComponent(baslaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bitirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sagUstPanelLayout.setVerticalGroup(
            sagUstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagUstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sagUstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baslaButton)
                    .addComponent(bitirButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sagUstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arastirilanLabel)
                    .addComponent(sayiLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        sagAltPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        sonucLabel.setText("Sonuç :");

        sonucArea.setEditable(false);
        sonucArea.setColumns(20);
        sonucArea.setRows(5);
        jScrollPane1.setViewportView(sonucArea);

        javax.swing.GroupLayout sagAltPanelLayout = new javax.swing.GroupLayout(sagAltPanel);
        sagAltPanel.setLayout(sagAltPanelLayout);
        sagAltPanelLayout.setHorizontalGroup(
            sagAltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagAltPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sagAltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sagAltPanelLayout.createSequentialGroup()
                        .addComponent(sonucLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap())
        );
        sagAltPanelLayout.setVerticalGroup(
            sagAltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagAltPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sonucLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(solPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sagUstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sagAltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sagUstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sagAltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(solPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslaButtonActionPerformed
        // butona bir kere basılması için
        if (start) {
            start = false;
            System.out.println("thread işlemleri başladı");
            Const.isRunning = false;
            th = createThread();
            th.start();
        }

    }//GEN-LAST:event_baslaButtonActionPerformed

    private Thread createThread() {
        return new Thread(new Runnable() {
            @Override
            public void run() {

                if (!Const.isRunning && isDone) {

                    isDone = false;
                    Const.isPrime = true;

                    System.out.println("Look for prime" + lookForPrime);

                    if (!Const.isFirstRun) {
                        lookForPrime += 2;
                    } else {
                        Const.isFirstRun = false;
                    }

                    sayiLabel.setText("" + lookForPrime);

                    sonucArea.setText("");

                    threadCount = (int) ((sql.primeCount((long) Math.sqrt(lookForPrime)) / 100.0) + 1); // Verilen formüle göre thread sayısı hesaplanıyor

                    // Eğer thread 1 ise 2 yapılıyor, eğer değilse normal bir şekilde devam ediliyor
                    if (threadCount == 1) {
                        threadCount = 2;
                    }

                    System.out.println("thread sayisi" + threadCount);

                    for (int i = 0; i < guiElements.size(); i++) {
                        guiElements.get(i).getjPanel().setVisible(false);
                        guiElements.get(i).getThreadLabel().setVisible(false);
                        guiElements.get(i).getDurumLabel().setVisible(false);
                        guiElements.get(i).getBitisLabel().setVisible(false);
                        guiElements.get(i).getBaslangicLabel().setVisible(false);
                    }

                    for (int i = 0; i < threadCount; i++) {
                        guiElements.get(i).getjPanel().setVisible(true);
                        guiElements.get(i).getThreadLabel().setVisible(true);
                        guiElements.get(i).getDurumLabel().setVisible(true);
                        guiElements.get(i).getBitisLabel().setVisible(true);
                        guiElements.get(i).getBaslangicLabel().setVisible(true);
                    }

                    // Tablodan getirilmiş asal sayılar
                    ArrayList<Long> dataList = sql.getDataFromTable((long) Math.sqrt(lookForPrime));

                    // Threadlerin hesap yapacağı aralık değeri belirleniyor
                    // Tablodaki asal sayı miktarının thread sayısına bölünmesi ile bulunuyor
                    int parse = (int) Math.floor((double) dataList.size() / threadCount);

                    System.out.println("parse " + parse);

                    // Thread Listesi temizleniyor
                    threadClassArrayList.clear();
                    int ceilIndex = 0;
                    // Threadler için belirlenen aralıkların tutulacağı liste
                    ArrayList<Long> newDataList = new ArrayList<>();

                    // Thread sayısının 1 eksiği kadar dönüyor
                    for (int i = 0; i < threadCount - 1; i++) {

                        // Thread numarasına göre tablodan çekilmiş olan liste
                        // parçalanıyor ve listeye ekleniyor
                        ceilIndex += parse;

                        for (int j = i * parse; j < ceilIndex; j++) {
                            newDataList.add(dataList.get(j));
                            System.out.println("Thread Veri eklendi no: " + j + " veri: " + dataList.get(j));
                        }

                        // Threadler belirlenen değerlere göre oluşturulup listeye ekleniyor
                        Thread thread = new Thread(new ThreadClass("Thread" + i, i, newDataList, lookForPrime, guiElements.get(i)));
                        threadClassArrayList.add(i, thread);

                        int size = newDataList.size() - 1;

                        guiElements.get(i).getThreadLabel().setText("Thread " + i);
                        guiElements.get(i).getBaslangicLabel().setText("" + newDataList.get(0));
                        guiElements.get(i).getBitisLabel().setText("" + newDataList.get(size));
                        guiElements.get(i).getDurumLabel().setText("True");
                        guiElements.get(i).getDurumLabel().setBackground(Color.green);
                    }

                    // Threadler için belirlenen aralıkların tutulacağı liste
                    newDataList = new ArrayList<>();

                    // Thread numarasına göre tablodan çekilmiş olan liste
                    // parçalanıyor ve listeye ekleniyor
                    int ceilIndex1 = dataList.size();
                    System.out.println("ceil : " + ceilIndex + " ceil1 : " + ceilIndex1);

                    for (int j = ceilIndex; j < ceilIndex1; j++) {
                        newDataList.add(dataList.get(j));
                    }

                    // Threadler belirlenen değerlere göre oluşturulup listeye ekleniyor
                    Thread thread = new Thread(new ThreadClass("Thread" + (threadCount - 1), (threadCount - 1), newDataList, lookForPrime, guiElements.get((threadCount - 1))));
                    threadClassArrayList.add((threadCount - 1), thread);

                    // guiElements.get(i).getjPanel().setVisible(true);
                    guiElements.get((threadCount - 1)).getThreadLabel().setText("Thread " + (threadCount - 1));
                    guiElements.get((threadCount - 1)).getDurumLabel().setText("True");
                    guiElements.get((threadCount - 1)).getBitisLabel().setText("" + newDataList.get(newDataList.size() - 1));
                    guiElements.get((threadCount - 1)).getBaslangicLabel().setText("" + newDataList.get(0));
                    guiElements.get((threadCount - 1)).getDurumLabel().setBackground(Color.green);

                    // ##################################################################
                    // Thread işlemlerini yap
                    // foreach ile listede tutulan threadler başlatılıyor
                    for (Thread thread1 : threadClassArrayList) {
                        thread1.start();
                    }

                    // Threadlerin bitip bitmediğinin kontrolünü yapan Thread
                    // Asal sayı bulan threadler ile birlikte çalışıp onların bitip bitmediğini kontrol ediyor
                    // İşlemler sonucunda tabloya değer yazılıp yazılmayacağının kontolünü yapıyor
                    Thread threadChecker = new Thread(new ThreadCheckerClass(threadClassArrayList, lookForPrime, sonucArea));
                    threadChecker.start();

                    while (Const.isRunning) {
                        //bos dongu
                    }
                    threadChecker.interrupt();
                    isDone = true;

                    try {
                        System.out.println("uyku girdi");
                        Thread.currentThread().sleep(3000);
                        System.out.println("uyku cıktı");

                        th = createThread();
                        th.start();

                    } catch (InterruptedException ex) {
                        Logger.getLogger(ThreadForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    private void bitirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirButtonActionPerformed
        // start false ise 
        if(!start) {
            start = true;
            System.out.println("thread işlemleri durduruldu");
            Const.isRunning = true;
        }
        
    }//GEN-LAST:event_bitirButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arastirilanLabel;
    private javax.swing.JButton baslaButton;
    private javax.swing.JLabel baslangicLabel;
    private javax.swing.JLabel baslangicLabel1;
    private javax.swing.JLabel baslangicLabel10;
    private javax.swing.JLabel baslangicLabel11;
    private javax.swing.JLabel baslangicLabel12;
    private javax.swing.JLabel baslangicLabel13;
    private javax.swing.JLabel baslangicLabel14;
    private javax.swing.JLabel baslangicLabel15;
    private javax.swing.JLabel baslangicLabel16;
    private javax.swing.JLabel baslangicLabel7;
    private javax.swing.JLabel baslangicLabel8;
    private javax.swing.JLabel baslangicLabel9;
    private javax.swing.JLabel baslangicYaziLabel;
    private javax.swing.JButton bitirButton;
    private javax.swing.JLabel bitisLabel;
    private javax.swing.JLabel bitisLabel1;
    private javax.swing.JLabel bitisLabel10;
    private javax.swing.JLabel bitisLabel11;
    private javax.swing.JLabel bitisLabel12;
    private javax.swing.JLabel bitisLabel13;
    private javax.swing.JLabel bitisLabel14;
    private javax.swing.JLabel bitisLabel15;
    private javax.swing.JLabel bitisLabel16;
    private javax.swing.JLabel bitisLabel7;
    private javax.swing.JLabel bitisLabel8;
    private javax.swing.JLabel bitisLabel9;
    private javax.swing.JLabel bitisYaziLabel;
    private javax.swing.JLabel durumLabel;
    private javax.swing.JLabel durumLabel1;
    private javax.swing.JLabel durumLabel10;
    private javax.swing.JLabel durumLabel11;
    private javax.swing.JLabel durumLabel12;
    private javax.swing.JLabel durumLabel13;
    private javax.swing.JLabel durumLabel14;
    private javax.swing.JLabel durumLabel15;
    private javax.swing.JLabel durumLabel16;
    private javax.swing.JLabel durumLabel7;
    private javax.swing.JLabel durumLabel8;
    private javax.swing.JLabel durumLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sagAltPanel;
    private javax.swing.JPanel sagUstPanel;
    private javax.swing.JLabel sayiLabel;
    private javax.swing.JPanel solPanel;
    private javax.swing.JTextArea sonucArea;
    private javax.swing.JLabel sonucLabel;
    private javax.swing.JLabel threadLabel;
    private javax.swing.JLabel threadLabel1;
    private javax.swing.JLabel threadLabel10;
    private javax.swing.JLabel threadLabel11;
    private javax.swing.JLabel threadLabel12;
    private javax.swing.JLabel threadLabel13;
    private javax.swing.JLabel threadLabel14;
    private javax.swing.JLabel threadLabel15;
    private javax.swing.JLabel threadLabel16;
    private javax.swing.JLabel threadLabel7;
    private javax.swing.JLabel threadLabel8;
    private javax.swing.JLabel threadLabel9;
    // End of variables declaration//GEN-END:variables
}
